# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fin-serv-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_fe768d99dd5d4511a8de092c8d1b7cd5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0db1f090597d45d7914f1a2ccf4cce15 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: ./src/
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fe768d99dd5d4511a8de092c8d1b7cd5 }}/martinobrecht/fin-serv-api:${{ github.sha }}
        file: ./src/FinServ.Api/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fin-serv-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f1f769c7e63e4edb8e23f4b17d5b9e16 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fe768d99dd5d4511a8de092c8d1b7cd5 }}/martinobrecht/fin-serv-api:${{ github.sha }}'
