# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fin-serv-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_9cef7b8fdbd9466fb5b30f9a538319ce }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a1704f3f8815408cb9a8c29bd85be740 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: ./src/
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9cef7b8fdbd9466fb5b30f9a538319ce }}/martinobrecht/fin-serv-api:${{ github.sha }}
        file: ./src/FinServ.Api/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fin-serv-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_730d5130487f4f90be79427e2619b67f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9cef7b8fdbd9466fb5b30f9a538319ce }}/martinobrecht/fin-serv-api:${{ github.sha }}'
